services:
  postgres:
    image: postgres:15
    container_name: mattersim_db
    environment:
      POSTGRES_USER: mattersim
      POSTGRES_PASSWORD: mattersim_password
      POSTGRES_DB: mattersim_dt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
